# Generated by Django 5.1.3 on 2025-01-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm_app', '0003_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
