# Generated by Django 5.1.3 on 2025-01-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm_app', '0005_contact_delete_specialoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
